twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
    globals:
        categoryRepository: '@App\Repository\CategoryRepository'
        cartService: '@App\Cart\CartService'
#    number_format:
#        decimal_point: ,
#        thousands_separator: ' '
